const API_URL =https://script.google.com/macros/library/d/1s3l_MO5ewOS73TN7vij2woIinuu3bEE7C8IhWOUPHbavT5kP7tr-sDhy/1;
let rawData=[];let filteredData=[];
const lokasiFilter=document.getElementById("lokasiFilter"),pemutusFilter=document.getElementById("pemutusFilter"),searchInput=document.getElementById("searchInput"),resetBtn=document.getElementById("resetBtn"),totalData=document.getElementById("totalData"),activeLokasi=document.getElementById("activeLokasi"),sumLokasi=document.getElementById("sumLokasi"),sumPemutus=document.getElementById("sumPemutus"),sumCt=document.getElementById("sumCt"),sumRelay=document.getElementById("sumRelay"),sumBeban=document.getElementById("sumBeban"),infoGrid=document.getElementById("infoGrid"),zoneGrid=document.getElementById("zoneGrid"),ocrRow=document.getElementById("ocrRow"),gfrRow=document.getElementById("gfrRow"),extraBox=document.getElementById("extraBox"),tableBody=document.getElementById("tableBody");
async function loadData(){try{const res=await fetch(API_URL);const json=await res.json();rawData=Array.isArray(json)?json:(json.data||[]);filteredData=[...rawData];buildFilters(rawData);renderTable(filteredData);updateCounters(filteredData);if(filteredData.length)showDetail(filteredData[0]);}catch(err){console.error(err);tableBody.innerHTML='<tr><td colspan="10" style="padding:20px;color:red;">Gagal memuat data. Cek URL Apps Script / akses web app.</td></tr>';}}
function buildFilters(data){const lokasiSet=new Set(),pemutusSet=new Set();data.forEach(d=>{if(d.lokasi)lokasiSet.add(d.lokasi);if(d.pemutus)pemutusSet.add(d.pemutus)});lokasiFilter.innerHTML='<option value="">Semua Lokasi</option>';[...lokasiSet].sort().forEach(v=>lokasiFilter.innerHTML+=`<option value="${v}">${v}</option>`);pemutusFilter.innerHTML='<option value="">Semua Pemutus</option>';[...pemutusSet].sort().forEach(v=>pemutusFilter.innerHTML+=`<option value="${v}">${v}</option>`);}
function applyFilters(){const lokasiVal=lokasiFilter.value.toLowerCase(),pemutusVal=pemutusFilter.value.toLowerCase(),keyword=searchInput.value.toLowerCase();filteredData=rawData.filter(item=>{const matchLokasi=!lokasiVal||(item.lokasi||"").toLowerCase().includes(lokasiVal);const matchPemutus=!pemutusVal||(item.pemutus||"").toLowerCase().includes(pemutusVal);const searchable=Object.values(item).join(" ").toLowerCase();const matchKeyword=!keyword||searchable.includes(keyword);return matchLokasi&&matchPemutus&&matchKeyword;});renderTable(filteredData);updateCounters(filteredData);if(filteredData.length)showDetail(filteredData[0]);else clearDetail();}
function renderTable(data){if(!data.length){tableBody.innerHTML='<tr><td colspan="10" style="padding:20px;">Data tidak ditemukan</td></tr>';return;}tableBody.innerHTML=data.map((d,i)=>`<tr data-index="${i}"><td>${d.no||""}</td><td>${d.lokasi||""}</td><td>${d.pemutus||""}</td><td>${d.merek||""}</td><td>${d.tipe||""}</td><td>${d.ct_ratio||""}</td><td>${d.relay||""}</td><td>${d.beban_kw||""}</td><td>${d.ocr_i||""}</td><td>${d.gfr_i||""}</td></tr>`).join("");document.querySelectorAll("#tableBody tr").forEach((row,idx)=>row.addEventListener("click",()=>showDetail(data[idx])));}
function showDetail(d){activeLokasi.textContent=d.lokasi||"-";sumLokasi.textContent=d.lokasi||"-";sumPemutus.textContent=d.pemutus||"-";sumCt.textContent=d.ct_ratio||"-";sumRelay.textContent=d.relay||"-";sumBeban.textContent=d.beban_kw||"-";infoGrid.innerHTML=`<div class="info-item"><span>Lokasi</span><strong>${d.lokasi||"-"}</strong></div><div class="info-item"><span>Pemutus</span><strong>${d.pemutus||"-"}</strong></div><div class="info-item"><span>Merek</span><strong>${d.merek||"-"}</strong></div><div class="info-item"><span>Tipe</span><strong>${d.tipe||"-"}</strong></div><div class="info-item"><span>CT Ratio</span><strong>${d.ct_ratio||"-"}</strong></div><div class="info-item"><span>Relay</span><strong>${d.relay||"-"}</strong></div><div class="info-item"><span>Beban (kW)</span><strong>${d.beban_kw||"-"}</strong></div>`;zoneGrid.innerHTML=`<div class="zone">Z1: ${d.z1||"-"}</div><div class="zone">Z2: ${d.z2||"-"}</div><div class="zone">Z3: ${d.z3||"-"}</div><div class="zone">Z4: ${d.z4||"-"}</div><div class="zone">Z5: ${d.z5||"-"}</div><div class="zone">Z6: ${d.z6||"-"}</div>`;ocrRow.innerHTML=`<td>${d.ocr_i||"-"}</td><td>${d.ocr_tms||"-"}</td><td>${d.ocr_curve||"-"}</td><td>${d.ocr_ii||"-"}</td><td>${d.ocr_delay||"-"}</td><td>${d.ocr_curve_hs||"-"}</td>`;gfrRow.innerHTML=`<td>${d.gfr_i||"-"}</td><td>${d.gfr_tms||"-"}</td><td>${d.gfr_curve||"-"}</td><td>${d.gfr_ii||"-"}</td><td>${d.gfr_delay||"-"}</td><td>${d.gfr_curve_hs||"-"}</td>`;extraBox.textContent=d.proteksi_tambahan||"Tidak ada proteksi tambahan";}
function clearDetail(){activeLokasi.textContent="-";sumLokasi.textContent="-";sumPemutus.textContent="-";sumCt.textContent="-";sumRelay.textContent="-";sumBeban.textContent="-";infoGrid.innerHTML='';zoneGrid.innerHTML='';ocrRow.innerHTML='<td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td>';gfrRow.innerHTML='<td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td>';extraBox.textContent='Belum ada data';}
function updateCounters(data){totalData.textContent=data.length}
function resetFilters(){lokasiFilter.value="";pemutusFilter.value="";searchInput.value="";filteredData=[...rawData];renderTable(filteredData);updateCounters(filteredData);if(filteredData.length)showDetail(filteredData[0]);else clearDetail();}
lokasiFilter.addEventListener("change",applyFilters);pemutusFilter.addEventListener("change",applyFilters);searchInput.addEventListener("input",applyFilters);resetBtn.addEventListener("click",resetFilters);loadData();
